language: python
python:
  - "3.12"

services:
  - postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE=mysite.settings
    - DATABASE_URL=postgres://postgres@localhost:5432/travis_ci_test

before_install:
  - pip install --upgrade pip
  - pip install --upgrade awscli

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - black --check .
  - flake8 .
  - coverage run --source='polls' manage.py test
  - coverage report
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-west-2
  bucket_name: elasticbeanstalk-us-west-2-908324163690
  app: djangotutorial-dev-v2
  env: djangotutorial-dev-v2-dev
  skip_cleanup: true
  on:
    branch: main


